{
	"version": 1748070287,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/bg-sheet0.png",
		"images/buah2-sheet0.png",
		"images/buah-sheet0.png",
		"images/buah-sheet1.png",
		"images/buah-sheet2.png",
		"images/mountain-sheet0.png",
		"images/mountain-sheet1.png",
		"images/skybnw-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground4.png",
		"images/tiledbackground5.png",
		"images/tiledbackground6.png",
		"images/onetimeplatform-sheet0.png",
		"images/cauldron-sheet0.png",
		"images/cauldron-sheet1.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/plx-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/cdformula-sheet0.png",
		"images/cdformula-sheet1.png",
		"images/elemen-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/buttonnext-sheet0.png",
		"images/spritefont.png",
		"images/sprite11-sheet0.png",
		"images/elemenpintu-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/buttoncontinue-sheet0.png",
		"images/spritefont2.png",
		"images/sprite10-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/pintu-sheet0.png",
		"images/bgmenu-sheet0.png",
		"images/startbt-sheet0.png",
		"images/optionsbt-sheet0.png",
		"images/petunjukbt-sheet0.png",
		"images/bglevel-sheet0.png",
		"images/levelbt-sheet0.png",
		"images/bgoptions-sheet0.png",
		"images/sfxon-sheet0.png",
		"images/exit-sheet0.png",
		"images/popup-sheet0.png",
		"images/levelend1-sheet0.png",
		"images/elemen2-sheet0.png",
		"images/elemen2-sheet1.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/formula-sheet0.png",
		"images/btmateri-sheet0.png",
		"images/tiledbackground.png",
		"images/question_block_pixel_art_smw_by_danyyer_dcjjlts-sheet0.png",
		"images/haduh-sheet0.png",
		"images/haduh2-sheet0.png",
		"images/flipbook-sheet0.png",
		"images/flipbook-sheet1.png",
		"images/flipbook-sheet2.png",
		"images/flipbook-sheet3.png",
		"images/btleft-sheet0.png",
		"images/btright-sheet0.png",
		"images/pohon-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/pertanyaan-sheet0.png",
		"images/centang-sheet0.png",
		"images/salah-sheet0.png",
		"images/lv1-sheet0.png",
		"images/lv2-sheet0.png",
		"images/lv3-sheet0.png",
		"images/lv4-sheet0.png",
		"images/elemenpintu2-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/heart-sheet0.png",
		"images/nyawa-sheet0.png",
		"images/gameover-sheet0.png",
		"images/gameover-sheet1.png",
		"images/gameover-sheet2.png",
		"images/sprite19-sheet0.png",
		"images/gameoverr-sheet0.png",
		"images/soalpresent-sheet0.png",
		"images/soalpresent-sheet1.png",
		"images/soalpresent-sheet2.png",
		"images/boxpresent-sheet0.png",
		"images/level2-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/kanan-sheet0.png",
		"images/kiri-sheet0.png",
		"images/jump-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/btsimplepresent-sheet0.png",
		"images/btimperativesentence-sheet0.png",
		"images/btsimplepast-sheet0.png",
		"images/btpastprogressive-sheet0.png",
		"images/chapter2-sheet0.png",
		"images/chapter2-sheet1.png",
		"images/chapter1-sheet0.png",
		"images/chapter1-sheet1.png",
		"images/chapter1-sheet2.png",
		"images/chapter3-sheet0.png",
		"images/chapter3-sheet1.png",
		"images/chapter4-sheet0.png",
		"images/chapter4-sheet1.png",
		"images/btback-sheet0.png",
		"images/soalpast-sheet0.png",
		"images/soalpast-sheet1.png",
		"images/soalpast-sheet2.png",
		"images/progressive-sheet0.png",
		"images/progressive-sheet1.png",
		"images/progressive-sheet2.png",
		"images/impresive-sheet0.png",
		"images/impresive-sheet1.png",
		"images/impresive-sheet2.png",
		"images/lv5-sheet0.png",
		"images/buahformula4-sheet0.png",
		"images/submitformula-sheet0.png",
		"images/fb-sheet0.png",
		"images/repeatbt-sheet0.png",
		"images/positipfb-sheet0.png",
		"images/bgfb-sheet0.png",
		"images/lanjutbt-sheet0.png",
		"images/negatipfb-sheet0.png",
		"images/tanyafb-sheet0.png",
		"images/tanyafb-sheet1.png",
		"images/btsubmit-sheet0.png",
		"images/dialog-sheet0.png",
		"images/popup2-sheet0.png",
		"images/donegame-sheet0.png",
		"images/donegame-sheet1.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/dialogawal-sheet0.png",
		"images/dialogawal-sheet1.png",
		"images/dialogawal-sheet2.png",
		"images/dialogawal-sheet3.png",
		"images/dialogawal-sheet4.png",
		"images/dialogawal-sheet5.png",
		"images/dialogawal-sheet6.png",
		"images/dialogawal-sheet7.png",
		"images/dialogawal-sheet8.png",
		"images/dialogawal-sheet9.png",
		"images/dialogawal-sheet10.png",
		"images/dialogawal-sheet11.png",
		"images/dialogawal-sheet12.png",
		"images/dialogawal-sheet13.png",
		"images/dialogawal-sheet14.png",
		"images/skip-sheet0.png",
		"images/nextdialogue-sheet0.png",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/walk-run.m4a",
		"media/walk-run.ogg",
		"media/fruit collect 1.m4a",
		"media/fruit collect 1.ogg",
		"media/select 1.m4a",
		"media/select 1.ogg",
		"media/big egg collect 1.m4a",
		"media/big egg collect 1.ogg",
		"media/confirm_style_1_001.m4a",
		"media/confirm_style_1_001.ogg",
		"media/confirm_style_3_001.m4a",
		"media/confirm_style_3_001.ogg",
		"media/meadowcabin (1).ogg",
		"media/main meny.m4a",
		"media/main meny.ogg",
		"media/no surem.m4a",
		"media/no surem.ogg",
		"media/mysterious forest music .m4a",
		"media/mysterious forest music .ogg",
		"media/track 8 - mother tree original.m4a",
		"media/track 8 - mother tree original.ogg",
		"media/pablocelva - chill! i'm just lookin'.m4a",
		"media/pablocelva - chill! i'm just lookin'.ogg",
		"media/goblins_dance_(battle).m4a",
		"media/goblins_dance_(battle).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}